**Vertical and Horizontal Image stacking**

In [15]:
import cv2
import numpy as np
import os

In [16]:
img = cv2.imread(r"D:\Computer-Vision\Computer_Vision\Images\img.jpg")
re_img = cv2.resize(img,(400,300))
cv2.imshow("Image_Window",re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
print(img)

[[[27 25 25]
  [26 24 24]
  [25 23 23]
  ...
  [24 21 23]
  [24 21 23]
  [24 21 23]]

 [[27 25 25]
  [26 24 24]
  [25 23 23]
  ...
  [24 21 23]
  [24 21 23]
  [24 21 23]]

 [[27 25 25]
  [26 24 24]
  [25 23 23]
  ...
  [24 21 23]
  [24 21 23]
  [24 21 23]]

 ...

 [[26 24 24]
  [26 24 24]
  [26 24 24]
  ...
  [36 34 34]
  [36 34 34]
  [36 34 34]]

 [[30 28 28]
  [30 28 28]
  [30 28 28]
  ...
  [36 34 34]
  [36 34 34]
  [36 34 34]]

 [[33 31 31]
  [33 31 31]
  [33 31 31]
  ...
  [36 34 34]
  [36 34 34]
  [36 34 34]]]


In [17]:
v = np.array([1,2,3,1,2,3]) 
np.hstack((v,v))

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [18]:
img = cv2.imread(r"D:\Computer-Vision\Computer_Vision\Images\img1.jpg")
re_img = cv2.resize(img,(400,300))
# h = np.hstack((re_img,re_img)) # Horizontal Stack 
v = np.vstack((re_img,re_img)) # Vertical Stack
# cv2.imshow("Image_Window_1",h)
cv2.imshow("Image_Window_1",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
img = cv2.imread(r"D:\Computer-Vision\Computer_Vision\Images\img1.jpg")
re_img = cv2.resize(img,(300,200))
h = np.hstack((re_img,re_img)) # Horizontal Stack 
v = np.vstack((h,h)) # Vertical Stack
# cv2.imshow("Image_Window_1",h)
cv2.imshow("Image_Window_1",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

**Slide Show**

In [20]:
list_name = os.listdir(r"D:\Computer-Vision\Computer_Vision\Images")
print(list_name)

['AI.mp4', 'Animal.jpg', 'Binary_1.jpg', 'Binary_2.jpg', 'close.png', 'ILLAHI.mp4', 'images.jpg', 'img.jpg', 'img1.jpg', 'img2.jpg', 'img3.jpg', 'img4.jpg', 'img5.jpg', 'img6.jpg', 'j.png', 'krishna.jpg', 'open.png', 'Ranbir.jpg', 'Ranbir_new.jpg', 'vid_to_img']


In [23]:
for name in list_name:
    path = r"D:\\Computer-Vision\\Computer_Vision\\Images" 
    img_name = path + "\\" + name
    img = cv2.imread(img_name)
    cv2.imshow("Image_Window_Slide",img)
    cv2.waitKey(1000)
cv2.destroyAllWindows()   


error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:973: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'
